Universe = vanilla
Notification = Error
Initialdir = /net/hisrv0001/home/mnguyen/scratch/CMSSW_3_9_1_patch1/src/MNguyen/InclusiveJetAnalyzer/test/
Executable = /bin/sh
Arguments = run_$(Process).sh 

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
# specify any extra input files (for example, an orcarc file)
transfer_input_files    =  inclusiveJetAnalyzer_Data_cfg.py, exec/run_$(Process).sh 

Log = /net/hisrv0001/home/mnguyen/logfiles/condor_$(Process).log
Output =/net/hisrv0001/home/mnguyen/logfiles/condor_$(Process).out
Error =/net/hisrv0001/home/mnguyen/logfiles/condor_$(Process).err

Notify_user =Matthew.Nguyen@cern.ch
GetEnv=True
+AccountingGroup="group_cmshi.mnguyen"
Queue 97

